### ISSUE TITLE
compiler warning

### ISSUE THREAD

**Issue by MasaoFujii** [uptimejp/sql_firewall#6]
Hi,

When I compiled this module on MacOS, I got the following compiler warning.

sql_firewall.c:232:39: warning: unused variable 'track_options' [-Wunused-const-variable]
static const struct config_enum_entry track_options[] =
                                      ^
1 warning generated.

Regards,

**Comment by snaga** [comment]
Thanks for the report.
Unfortunately, I don't have OSX to reproduce that, so could you please try this patch (1a404a593b78681a4181920ff3935320bc9df17f) to fix that?
If it can fix that, I will merge to the develop branch.

**Comment by MasaoFujii** [comment]
Thanks for the patch! This works for me.

**Comment by snaga** [comment]
Merged. bb5397373fb5556e8d4540446f8b5f9ce272c7f7
